#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

blockMesh > blockMesh.log
snappyHexMesh -overwrite > snappyhexMesh.log
topoSet > topoSet.log
createPatch -overwrite > createPatch.log
touch 2_snappy_pipe.foam
