#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

blockMesh > blockMesh.log
snappyHexMesh -overwrite > snappyhexMesh.log
icoFoam
touch 1_snappy_pipe.foam
